apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"

# to have this applied, restart the argocd-server deployment:
# kubectl scale -n argocd deployment/argocd-server --replicas=0
# kubectl scale -n argocd deployment/argocd-server --replicas=1
