apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea 
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
        - name: gitea.admin.username 
          value: "till"
        - name: gitea.admin.email
          value: "till.meyerzuwestram@zuehlke.com"
        - name: gitea.config.APP_NAME
          value: "argocd gitea"
        - name: gitea.config.server.DOMAIN
          value: "gitea.{{ .Values.spec.domain }}"
        - name: gitea.config.server.SSH_DOMAIN
          value: "gitea.{{ .Values.spec.domain }}"
        - name: service.ssh.type
          value: "NodePort"
        - name: service.ssh.nodePort
          value: "32767"
      # - name: gitea.config.server.ROOT_URL
      #   value: "https://gitea.{{ .Values.spec.domain }}"
    chart: gitea
    repoURL: https://dl.gitea.io/charts/
    targetRevision: 4.0.3 
    path: gitea 
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: default


---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress-route 
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`gitea.{{ .Values.spec.domain }}`)
    kind: Rule
    services:
    - name: gitea-http 
      port: 3000
      #targetPort: 80

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: gitea-ssh-nodeport
#  namespace: default
#spec:
#  type: NodePort
#  ports:
#    - port: 22
#      targetPort: 22
#      nodePort: 22
#      protocol: TCP
#  selector:
#    name: gitea-ssh

