apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb 
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.repo }}
    targetRevision: HEAD
    path: metallb 
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: default 

