apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik 
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik 
    repoURL: https://helm.traefik.io/traefik 
    targetRevision: 10.3.2
    path: traefik 
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`*`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
