apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.repo }} 
    targetRevision: HEAD
    path: whoami
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: default

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-route 
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`whoami.{{ .Values.spec.domain }}`)
    kind: Rule
    services:
    - name: whoami
      port: 80 
      #targetPort: 80
